apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frepai-srs-ingress
  namespace: frepai
  annotations:
    kubernetes.io/ingress.class: 'nginx'
    nginx.ingress.kubernetes.io/ssl-redirect: 'false'
    nginx.ingress.kubernetes.io/force-ssl-redirect: 'false'
    nginx.ingress.kubernetes.io/enable-cors: 'true'
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/cors-allow-methods: '*'
    nginx.ingress.kubernetes.io/cors-allow-headers: '*'
    nginx.ingress.kubernetes.io/cors-allow-credentials: 'true'
spec:
  tls:
  - hosts:
    - srs.hzcsdata.com
    secretName: srs-hzcsdata-tls

  rules:
  - host: srs.hzcsdata.com
    http:
      paths:
        - pathType: Prefix
          path: /
          backend:
            service:
              name: srs-service
              port:
                number: 80
